package edu.csc131.FlightPlan;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.maps.DistanceMatrixApi;

import com.google.maps.GeoApiContext;
import com.google.maps.model.DistanceMatrix;
import com.google.maps.model.TravelMode;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

@Controller // This means that this class is a Controller
@RequestMapping(path="/flightPlan") // This means URL's start with /flightPlan (after Application path)
public class surverController {
    @Autowired // This means to get the bean called DataRepo
    // Which is auto-generated by Spring, we will use it to handle the data
    private DataRepo dataRepo;
    private UserData n = new UserData();
    
    @PostMapping(path="/takeFlight") // Map ONLY POST Requests
    public String saveData (@RequestParam String address, @RequestParam double mpg, @RequestParam("insRate") double insurenceRate) {
      // @ResponseBody means the returned String is the response, not a view name
      // @RequestParam means it is a parameter from the GET or POST request

      TimeTo time = new TimeTo(address);
      String travelTimeByCar = time.getTimeByCar();
      String travelTimeByWalk = time.getTimeByWalking();

  
      
      n.setAddress(address);
      n.settravelTimeByCar(travelTimeByCar);
      n.setTravelTimeByWalking(travelTimeByWalk);
      n.setInsurenceRate(insurenceRate);
      n.setMpg(mpg);



      dataRepo.save(n);
      return "redirect:/flightPlan/results";
    }

    @GetMapping(path="/results")
    public String getResults(Model model) {
      //ModelAndView mv = new ModelAndView();
      model.addAttribute("address", n.getAddress());
      model.addAttribute("travelTimeByCar", n.gettravelTimeByCar());
      model.addAttribute("travelTimeByWalking", n.getTravelTimeByWalking());
      model.addAttribute("mpg", n.getMpg());
      model.addAttribute("insurenceRate", n.getInsurenceRate());
      
      return "/takeFlight.html";
  }
}

