package edu.csc131.FlightPlan;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

/**
 * <i>Here be dragons.</i> This class contains the controler for flightPlan. It
 * contains the post and get methods. We are using Spring. It is a framework
 * that heavely uses anotations to do a lot of fancy things, really rather
 * easiely.
 * 
 * @author ingrumm
 */
@Controller // This means that this class is a Controller
@RequestMapping(path = "/flightPlan") // This means URL's start with /flightPlan (after Application path)
public class surverController {
  @Autowired // This means to get the bean called DataRepo
             // Which is auto-generated by Spring, we will use it to handle the data
  private DataRepo dataRepo;// This is the repo object. You use it to save or load objects.
  private UserData userData = new UserData();// This is the User Data object. We store this object in the database.
                                             // Neat!

  /**
   * All params are from request attrbutes.
   * 
   * @param address
   * @param mpg
   * @param insurenceRate
   * @return Forward to Get mapped function.
   */
  @PostMapping(path = "/takeFlight") // Map ONLY POST Requests
  public String saveData(@RequestParam String address, @RequestParam double mpg,
      @RequestParam("insRate") double insurenceRate) {
    // @RequestParam means it is a parameter from the GET or POST request. Here we
    // are using POST.

    // Creates a TimeTo object. This class will give us the time to a destnation.
    // We can also add functionality to get distance as well.

    TimeTo time;
    try {
      time = new TimeTo(address);
    } catch (NotValidAddressException e) {

      e.printStackTrace();
      return "/invalidAddress";
    }
    // Get times
    String travelTimeByCar = time.getTimeByCar();
    String travelTimeByWalk = time.getTimeByWalking();

    //TODO add transportation travel tiem
    //TODO add bicycle travel time

    userData.setAddress(address);
    userData.settravelTimeByCar(travelTimeByCar);
    userData.setTravelTimeByWalking(travelTimeByWalk);
    userData.setInsurenceRate(insurenceRate);
    userData.setMpg(mpg);

    // adds the row to the database.
    dataRepo.save(userData);

    // redirects to class member mapped to /results
    return "redirect:/flightPlan/results";
  }

  /**
   * 
   * @param model
   * @return Returns the View called takeFlight.html
   * 
   *         We set can add attrbutes to the model here. Thymeleaf then parses our
   *         html file, and replaces the corrasponding variables. We can also do
   *         this with a jsp file instead og an htm file. That gives us more toys,
   *         but I had trouble with Spring serving the file correctly.
   */
  @GetMapping(path = "/results")
  public String getResults(Model model) {
    // ModelAndView mv = new ModelAndView();
    model.addAttribute("address", userData.getAddress());
    model.addAttribute("travelTimeByCar", userData.gettravelTimeByCar());
    model.addAttribute("travelTimeByWalking", userData.getTravelTimeByWalking());
    model.addAttribute("mpg", userData.getMpg());
    model.addAttribute("insurenceRate", userData.getInsurenceRate());

    return "/takeFlight.html";
  }
}
